Repository rollbar/rollbar-flutter, pull requests merged in 2022-04, with the labels that each got.

#22 docs: Add missing import to example code
  rollbar_flutter/README.md
Labels: documentation

#16 exclude arm64 slice for the iOS simulator
  rollbar_flutter/ios/rollbar_flutter.podspec
Labels: cocoapods, ios

#18 Connectivity monitor
  .gitignore
  .vscode/extensions.json
  rollbar_common/.gitignore
  rollbar_common/CHANGELOG.md
  rollbar_common/README.md
  rollbar_common/analysis_options.yaml
  rollbar_common/lib/rollbar_common.dart
  rollbar_common/lib/src/_internal/module.dart
  rollbar_common/lib/src/connectivity_monitor.dart
  rollbar_common/lib/src/design_patterns/Readme.md
  rollbar_common/lib/src/design_patterns/gof_creational/singleton.dart
  rollbar_common/lib/src/logging.dart
  rollbar_common/lib/src/sdk_logger.dart
  rollbar_common/lib/src/service_locator.dart
  rollbar_common/pubspec.yaml
  rollbar_common/test/_internal/module_logger_test.dart
  rollbar_common/test/service_locator_test.dart
  rollbar_dart/example/bin/rollbar_dart_example.dart
  rollbar_dart/example/pubspec.yaml
  rollbar_dart/lib/rollbar.dart
  rollbar_dart/lib/src/_internal/module.dart
  rollbar_dart/lib/src/api/response.dart
  rollbar_dart/lib/src/config.dart
  rollbar_dart/lib/src/connectivity_monitor.dart
  rollbar_dart/lib/src/core_notifier.dart
  rollbar_dart/lib/src/http_sender.dart
  rollbar_dart/lib/src/payload_repository/ReadMe.md
  rollbar_dart/lib/src/payload_repository/db_data_access.dart
  rollbar_dart/lib/src/payload_repository/destination.dart
  rollbar_dart/lib/src/payload_repository/payload_record.dart
  rollbar_dart/lib/src/payload_repository/payload_repository.dart
  rollbar_dart/lib/src/persistent_sender.dart
  rollbar_dart/lib/src/rollbar.dart
  rollbar_dart/lib/src/rollbar_infrastructure.dart
  rollbar_dart/lib/src/sdk_dart_logger.dart
  rollbar_dart/lib/src/sender.dart
  rollbar_dart/lib/src/uncaught_error.dart
  rollbar_dart/pubspec.yaml
  rollbar_dart/test/_internal/module_logger_test.dart
  rollbar_dart/test/client_server_utils.dart
  rollbar_dart/test/connectivity_monitor_test.dart
  rollbar_dart/test/http_sender_test.dart
  rollbar_dart/test/payload_repository/db_data_access_test.dart
  rollbar_dart/test/payload_repository/payload_repository_test.dart
  rollbar_dart/test/rollbar_live_test.dart
  rollbar_dart/test/rollbar_test.dart
  rollbar_dart/test/uncaught_error_handler_test.dart
  rollbar_flutter/lib/rollbar.dart
  rollbar_flutter/lib/src/_internal/module.dart
  rollbar_flutter/lib/src/connectivity_monitor.dart
  rollbar_flutter/pubspec.yaml
  rollbar_flutter/test/_internal/module_logger_test.dart
  rollbar_flutter/test/connectivity_monitor_test.dart
  rollbar_flutter/test/rollbar_flutter_test.dart
Labels: enhancement
